[package]
name = "clone-factory"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"
egui_extras = { version = "0.30.0", features = ["all_loaders"] }
serde = "1.0.217"
serde_derive = "1.0.217"
toml = "0.8.19"
