[package]
name = "clone-factory"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = { version = "0.29.0",  features = ["serde"]}
serde = "1.0.217"
serde_derive = "1.0.217"
toml = "0.8.19"
