[item_appearances]
[actor_appearances]
[actor_appearances.player]
    glyph = "@"
    glyph_n = "A"
    glyph_s = "V"
    glyph_e = ">"
    glyph_w =  "<"
    color = "red"

[actor_appearances.clone]
    glyph = "@"
    glyph_n = "A"
    glyph_s = "V"
    glyph_e = ">"
    glyph_w =  "<"
    color = "white"

[buildings]

[buildings.crystal_deposit]
    name = "Crystal deposit"
    description = "All the crystal you could ever want"
    on_interact = "building_mine"
    glyph = "O"
    color = "blue"

[buildings.matter_digitizer]
    name = "Matter Digitizer"
    description = "Magically make items vanish"
    on_interact = "building_digitize"
    glyph = "Y"
    color = "blue"

[items]
[items.recorder]
    name = "Empty Recorder"
    id = 2
    description = "an empty recording item"
    on_use = "action_special_start_record"
    glyph = "ꙮ"
    color = "blue"

[items.raw_crystal]
    name = "Raw Crystal"
    id = 0
    description = "TODO"
    glyph = "*"
    color = "grey"

[items.basic_cloner]
    name = "Basic cloner"
    id = 4
    description = "Spawns a clone of you"
    on_use = "action_use_cloner"
    glyph = "@"
    color = "blue"

[items.echo_crystal]
    name = "Echo Crystal"
    id = 1
    description = "TODO"
    glyph = "*"
    color = "grey"
    score_value = 1

[recipes]
[recipes.echo_crystal]
    ingredients = ["raw_crystal"]
    ingredient_counts = [1]
    product = "echo_crystal"
    product_count = 1
    name = "Echo Crystal"

[recipes.recorder]
    ingredients = ["echo_crystal"]
    ingredient_counts = [1]
    product = "recorder"
    product_count = 1
    name = "Empty Recorder"
