[actors]
[actors.player]
    name = "player"
[actors.player.text]
    name = "Player"
    description = "It's you."
[actors.player.appearance]    
    glyph = "@"
    glyph_n = "A"
    glyph_s = "V"
    glyph_e = ">"
    glyph_w =  "<"
    color = "red"

[actors.clone]
    name = "clone"
    hp = 30
[actors.clone.text]
    name = "clone"
    description = "It's your doppleganger."
[actors.clone.appearance]    
    glyph = "@"
    glyph_n = "A"
    glyph_s = "V"
    glyph_e = ">"
    glyph_w =  "<"
    color = "white"


[buildings]
[buildings.crystal_deposit]
    name = "crystal_deposit"
    on_interact = "building_mine"
[buildings.crystal_deposit.text]
    name = "Crystal Deposit"
    description = "All the crystal you could ever want"
[buildings.crystal_deposit.appearance]
    glyph = "O"
    color = "blue"

[buildings.matter_digitizer]
    name = "crystal_deposit"
    on_interact = "building_digitize"
[buildings.matter_digitizer.text]
    name = "Matter Digitizer"
    description = "Converts items into score. Reduces local paradox levels."
[buildings.matter_digitizer.appearance]
    glyph = "Y"
    color = "blue"

[items.recorder]
    name = "recorder"
    on_use = "action_special_start_record"
[items.recorder.text]
    name = "Empty Recorder"
    description = "an empty recording item"
[items.recorder.appearance]
    glyph = "ꙮ"
    color = "blue"

[items.raw_crystal]
    name = "raw_crystal"
    on_use = "action_special_start_record"
[items.raw_crystal.text]
    name = "Raw Crystal"
    description = "Basic ore."
[items.raw_crystal.appearance]
    glyph = "*"
    color = "grey"

[items.basic_cloner]
    name = "basic_cloner"
    on_use = "action_use_cloner"
[items.basic_cloner.text]
    name = "Basic cloner"
    description = "Spawns clones of yourself."
[items.basic_cloner.appearance]
    glyph = "@"
    color = "blue"

[items.echo_crystal]
    name = "echo_crystal"
    score_value = 1
[items.echo_crystal.text]
    name = "Echo Crystal"
    description = "A crafting material. Worth 1 score."
[items.echo_crystal.appearance]
    glyph = "*"
    color = "grey"

[items.matter_digitizer]
    name = "matter_digitizer"
    on_use = "action_construct"
[items.matter_digitizer.text]
    name = "Matter Digitizer"
    description = "Building. Worth 5 score. Converts items into score. Reduces local paradox levels."
[items.matter_digitizer.appearance]
    glyph = "Y"
    color = "grey"

[recipes]
[recipes.echo_crystal]
    ingredients = ["raw_crystal"]
    ingredient_counts = [1]
    product = "echo_crystal"
    product_count = 1
    name = "Echo Crystal"

[recipes.recorder]
    ingredients = ["echo_crystal"]
    ingredient_counts = [1]
    product = "recorder"
    product_count = 1
    name = "Empty Recorder"

[recipes.matter_digitizer]
    ingredients = ["echo_crystal"]
    ingredient_counts = [5]
    product = "matter_digitizer"
    product_count = 1
    name = "Matter Digitizer"
